/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.gui;

import br.edu.ifnmg.gui.*;
import br.edu.ifnmg.book.Book;
import br.edu.ifnmg.book.BookDao;
import br.edu.ifnmg.commets.Comments;
import br.edu.ifnmg.commets.CommentsDao;
import br.edu.ifnmg.credential.Credential;
import br.edu.ifnmg.reader.Reader;
import br.edu.ifnmg.reader.ReaderDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaok
 */
public class Comentarios extends javax.swing.JFrame {

    /**
     * Creates new form ComentariosLivro
     */
    private static Comentarios instance;
    public static Credential cred = null;

    public Comentarios() {
        initComponents();
        // Centralização da janela
        setLocationRelativeTo(null);
        lblcomentado.setVisible(false);
        lblSelecione.setVisible(false);
        lblSoLeitores.setVisible(false);
        comentariosBookTable();
    }

    public static Comentarios getInstance() {
        if (instance == null) {
            instance = new Comentarios();
        }

        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtualiza = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivro = new javax.swing.JTable();
        lblTdsLivros = new javax.swing.JLabel();
        lblSelecione = new javax.swing.JLabel();
        lblcomentado = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnComentar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        lblSoLeitores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualizar Livro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tableLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Titulo", "Autor", "Páginas", "Ano", "Edição"
            }
        ));
        jScrollPane1.setViewportView(tableLivro);

        lblTdsLivros.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblTdsLivros.setText("Livros Cadrastrados");

        lblSelecione.setForeground(new java.awt.Color(240, 0, 0));
        lblSelecione.setText("Selecione um Livro");

        lblcomentado.setForeground(new java.awt.Color(0, 0, 255));
        lblcomentado.setText("Livro Comentado Com Sucesso!!");

        lblTitulo.setText("Comentários:");

        btnComentar.setText("Comentar");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        jScrollPane2.setViewportView(txtComentario);

        lblSoLeitores.setForeground(new java.awt.Color(240, 0, 0));
        lblSoLeitores.setText("Comentários Apenas Para Leitores!!");

        javax.swing.GroupLayout panelAtualizaLayout = new javax.swing.GroupLayout(panelAtualiza);
        panelAtualiza.setLayout(panelAtualizaLayout);
        panelAtualizaLayout.setHorizontalGroup(
            panelAtualizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtualizaLayout.createSequentialGroup()
                .addGroup(panelAtualizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtualizaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAtualizaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblTdsLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelAtualizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtualizaLayout.createSequentialGroup()
                        .addGroup(panelAtualizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtualizaLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(btnComentar))
                            .addGroup(panelAtualizaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelAtualizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addGroup(panelAtualizaLayout.createSequentialGroup()
                                        .addComponent(lblTitulo)
                                        .addGap(210, 210, 210)))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtualizaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAtualizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtualizaLayout.createSequentialGroup()
                                .addComponent(lblcomentado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtualizaLayout.createSequentialGroup()
                                .addComponent(lblSelecione)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtualizaLayout.createSequentialGroup()
                                .addComponent(lblSoLeitores)
                                .addGap(49, 49, 49))))))
        );
        panelAtualizaLayout.setVerticalGroup(
            panelAtualizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtualizaLayout.createSequentialGroup()
                .addGroup(panelAtualizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtualizaLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcomentado)
                        .addGap(18, 18, 18)
                        .addComponent(btnComentar))
                    .addGroup(panelAtualizaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAtualizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTdsLivros)
                            .addComponent(lblSelecione))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAtualizaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblSoLeitores)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(panelAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAtualiza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        lblSelecione.setVisible(false);
        lblcomentado.setVisible(false);

        this.setVisible(false);
        TelaPrincipal.getInstance(TelaPrincipal.current_cred).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableLivro.getSelectedRow();
        if (selectedRow != -1) {
            Long selectedId = (Long) tableLivro.getValueAt(selectedRow, 0);
            comentariosBook(selectedId);
            txtComentario.setText("");
            lblSelecione.setVisible(false);
            comentariosBookTable();
        } else {
            System.out.println("Selecione um livro antes de adicionar um comentário.");
            lblSelecione.setVisible(true);
            lblcomentado.setVisible(false);
        }
    }//GEN-LAST:event_btnComentarActionPerformed

    private void comentariosBookTable() {
        try {
            BookDao bookDao = new BookDao();
            List<Book> books = bookDao.findAll();

            DefaultTableModel model = (DefaultTableModel) tableLivro.getModel();
            model.setRowCount(0);

            for (Book book : books) {
                Object[] rowData = {
                    book.getId(),
                    book.getTitle(),
                    book.getAuthors(),
                    book.getPages(),
                    book.getYear(),
                    book.getEdition(),};
                model.addRow(rowData);
            }

            // Adiciona um listener para a tabela
            tableLivro.getSelectionModel().addListSelectionListener(e -> {
                int selectedRow = tableLivro.getSelectedRow();
                if (selectedRow != -1) {
                    // Obtém os dados da linha selecionada, incluindo o ID
                    Long selectedId = (Long) tableLivro.getValueAt(selectedRow, 0);

                    lblSelecione.setVisible(false);
                    lblcomentado.setVisible(false);
                    lblSoLeitores.setVisible(false);
                }
            });
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void comentariosBook(Long selectedId) {
        try {
            if (selectedId != null) {
                String comentario = txtComentario.getText();

                BookDao bookDao = new BookDao();
                Book livro = bookDao.findById(selectedId);

                if (livro != null) {
                    // Adiciona um comentário ao livro
                    CommentsDao commentsDao = new CommentsDao();

                    Long readerId = cred.getUser().getId();
                    ReaderDao readerDao = new ReaderDao();
                    Reader reader = readerDao.findById(readerId);

                    if (reader != null) {
                        Comments comment = new Comments(null, comentario, livro, reader);
                        commentsDao.saveOrUpdate(comment);
                        System.out.println("Comentário adicionado com sucesso!");
                        lblcomentado.setVisible(true);
                    } else {
                        System.out.println("Leitor não encontrado");
                        lblSoLeitores.setVisible(true);
                    }
                } else {
                    System.out.println("Livro não encontrado para adicionar comentário");
                }
            } else {
                System.out.println("Selecione um livro antes de adicionar um comentário");
                lblSelecione.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comentarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSelecione;
    private javax.swing.JLabel lblSoLeitores;
    private javax.swing.JLabel lblTdsLivros;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblcomentado;
    private javax.swing.JPanel panelAtualiza;
    private javax.swing.JTable tableLivro;
    private javax.swing.JTextArea txtComentario;
    // End of variables declaration//GEN-END:variables
}
