/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifnmg.gui;

import br.edu.ifnmg.book.Book;

/**
 *
 * @author ketsu
 */
public class LivroPanel extends javax.swing.JPanel {

    /**
     * Creates new form LivroPanel
     */
    public LivroPanel(Book book) {
        initComponents();
        lblAno.setText(book.getYear().toString());
        lblAutor.setText(book.getAuthors());
        lblEdition.setText(book.getEdition().toString());
        lblPages.setText(book.getPages().toString());
        lblTitle.setText(book.getTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPages = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblEdition = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();

        lblPages.setText("Paginas");

        lblTitle.setText("Titulo");

        lblEdition.setText("Edição");

        lblAutor.setText("Autor");

        lblAno.setText("Ano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(50, 50, 50)
                .addComponent(lblAutor)
                .addGap(50, 50, 50)
                .addComponent(lblAno)
                .addGap(50, 50, 50)
                .addComponent(lblEdition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lblPages)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPages)
                    .addComponent(lblEdition)
                    .addComponent(lblAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAno)
                    .addComponent(lblTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblEdition;
    private javax.swing.JLabel lblPages;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
