/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.gui;

import br.edu.ifnmg.credential.Credential;

/**
 *
 * @author joaok
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public static Credential current_cred = null;
    /**
     * Creates new form TelaPrincipal
     */
    private static TelaPrincipal instance;

    public TelaPrincipal() {
        initComponents();
    }

    public static TelaPrincipal getInstance(Credential credential) {

        if (instance == null) {
            instance = new TelaPrincipal();
            //current_cred=credential;
        }

        //<editor-fold defaultstate="collapsed" desc="Ativação/Desativação de menus">
        // Escolha entre ocultar
        // Perceba que a própria classe pode ter acesso direto a seus atributos
        // privados. Por isso não houve um ...getMnuCadastroUsuario()
//        
        if (current_cred.getUser().getRole().getName().equals("administrador")) {
            instance.menuVerUsuario.setVisible(true);
            instance.menuCadUsuario.setVisible(true);
            instance.menuCadLivro.setVisible(true);
            instance.menuLivro.setVisible(true);
            instance.menuCadEmp.setVisible(true);
            instance.menuHistoryEmp.setVisible(true);
            instance.menuAutoEmp.setVisible(true);
            instance.setTitle("Library System - " + current_cred.getUser().getName());

        } else if (current_cred.getUser().getRole().getName().equals("bibliotecário")) {
            instance.menuVerUsuario.setVisible(true);
            instance.menuCadUsuario.setVisible(false);
            instance.menuCadLivro.setVisible(true);
            instance.menuLivro.setVisible(true);
            instance.menuCadEmp.setVisible(true);
            instance.menuHistoryEmp.setVisible(false);
            instance.menuAutoEmp.setVisible(false);
            instance.setTitle("Library System - " + current_cred.getUser().getName());

        } else if (current_cred.getUser().getRole().getName().equals("leitor")) {
            instance.menuVerUsuario.setVisible(true);
            instance.menuCadUsuario.setVisible(false);
            instance.menuCadLivro.setVisible(false);
            instance.menuLivro.setVisible(true);
            instance.menuCadEmp.setVisible(false);
            instance.menuHistoryEmp.setVisible(true);
            instance.menuAutoEmp.setVisible(true);
            instance.setTitle("Library System - " + current_cred.getUser().getName());

        }
        System.out.println(current_cred.getUser());

//        instance.menuCadLivro.setVisible(credential.getUser().getRole().getName().equals("biblioteca"));
//        instance.menuCadEmp.setVisible(credential.getUser().getRole().getName().equals("biblioteca"));
//        instance.setTitle("Library System - " + credential.getUser().getName());
        // ... ou desabilitar
        //</editor-fold>
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuVerUsuario = new javax.swing.JMenuItem();
        menuCadUsuario = new javax.swing.JMenuItem();
        menuBook = new javax.swing.JMenu();
        menuCadLivro = new javax.swing.JMenuItem();
        menuLivro = new javax.swing.JMenuItem();
        menuEmpres = new javax.swing.JMenu();
        menuCadEmp = new javax.swing.JMenuItem();
        menuHistoryEmp = new javax.swing.JMenuItem();
        menuAutoEmp = new javax.swing.JMenuItem();
        menuUsuario1 = new javax.swing.JMenu();
        menuVerUsuario1 = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(64, 64, 64));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Quando Leitor, implementar Histórico aqui");

        jLabel2.setText("Quando Biblitecario, mostrar livros aqui :D;  Implementar Classe LivroMenu");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        menu.setBackground(new java.awt.Color(64, 64, 64));
        menu.setBorder(null);
        menu.setBorderPainted(false);

        menuUsuario.setBackground(new java.awt.Color(70, 70, 70));
        menuUsuario.setText("Usuário");

        menuVerUsuario.setText("Usuário");
        menuVerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuVerUsuario);

        menuCadUsuario.setText("Cadrastro de Usuário");
        menuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuCadUsuario);

        menu.add(menuUsuario);

        menuBook.setBackground(new java.awt.Color(70, 70, 70));
        menuBook.setText("Livro");

        menuCadLivro.setText("Cadastro de Livro");
        menuBook.add(menuCadLivro);

        menuLivro.setText("Livros");
        menuBook.add(menuLivro);

        menu.add(menuBook);

        menuEmpres.setText("Empréstimo");

        menuCadEmp.setText("Cadastro de Empréstimo");
        menuCadEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadEmpActionPerformed(evt);
            }
        });
        menuEmpres.add(menuCadEmp);

        menuHistoryEmp.setText("Historico Empréstimo");
        menuHistoryEmp.setBorderPainted(false);
        menuHistoryEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistoryEmpActionPerformed(evt);
            }
        });
        menuEmpres.add(menuHistoryEmp);
        menuHistoryEmp.getAccessibleContext().setAccessibleName("");

        menuAutoEmp.setText("Autoriza Empréstimo");
        menuEmpres.add(menuAutoEmp);

        menu.add(menuEmpres);

        menuUsuario1.setBackground(new java.awt.Color(70, 70, 70));
        menuUsuario1.setText("Ajuda");

        menuVerUsuario1.setText("Sobre");
        menuVerUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerUsuario1ActionPerformed(evt);
            }
        });
        menuUsuario1.add(menuVerUsuario1);

        menu.add(menuUsuario1);

        setJMenuBar(menu);
        menu.getAccessibleContext().setAccessibleName("Library System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelPrincipal.getAccessibleContext().setAccessibleName("Library System");

        getAccessibleContext().setAccessibleName("Library System");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Login.getInstance().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void menuVerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVerUsuarioActionPerformed

    private void menuHistoryEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistoryEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHistoryEmpActionPerformed

    private void menuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadUsuarioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        CadrastroUsuario.getInstance().setVisible(true);
    }//GEN-LAST:event_menuCadUsuarioActionPerformed

    private void menuCadEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadEmpActionPerformed

    private void menuVerUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVerUsuario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuAutoEmp;
    private javax.swing.JMenu menuBook;
    private javax.swing.JMenuItem menuCadEmp;
    private javax.swing.JMenuItem menuCadLivro;
    private javax.swing.JMenuItem menuCadUsuario;
    private javax.swing.JMenu menuEmpres;
    private javax.swing.JMenuItem menuHistoryEmp;
    private javax.swing.JMenuItem menuLivro;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuUsuario1;
    private javax.swing.JMenuItem menuVerUsuario;
    private javax.swing.JMenuItem menuVerUsuario1;
    // End of variables declaration//GEN-END:variables
}
